language: node_js
node_js:
- '8'
- '6'
- '4.5.0'
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

matrix:
  include:
  - os: linux
    compiler: g++-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - COMPILER_OVERRIDE="CXX=g++-6 CC=gcc-6"

before_install:
- |
  if [ $TRAVIS_OS_NAME == linux ]; then
    if [ "$COMPILER_OVERRIDE" == "" ]; then
      #use g++5 by default
      export CXX="g++-5" CC="gcc-5"
    else
      export ${COMPILER_OVERRIDE}
    fi
  fi
install:
- npm install cmake-js -g
- npm install
script:
- npm test
- npm run unittest
after_success:
- npm run benchmark
